// Full GCSR navigation: 15 modules × 120 screens
// Icons: lucide-react names

export const NAV = [
  {
    id: 'exec',
    label: 'Executive Command',
    icon: 'LayoutDashboard',
    color: '#1E3A8A',
    items: [
      { id: 7,  path: '/dashboard/state',       label: 'State Dashboard',        icon: 'Landmark' },
      { id: 8,  path: '/dashboard/district',    label: 'District Dashboard',     icon: 'MapPin' },
      { id: 9,  path: '/dashboard/department',  label: 'Department Dashboard',   icon: 'Building2' },
      { id: 10, path: '/dashboard/data-lake',   label: 'Data Lake Health',       icon: 'Waves' },
      { id: 11, path: '/dashboard/data-quality',label: 'Data Quality',           icon: 'ShieldCheck' },
      { id: 12, path: '/dashboard/ai',          label: 'AI Governance',          icon: 'Brain' },
      { id: 13, path: '/dashboard/citizen',     label: 'Citizen & Family KPIs',  icon: 'Users' },
      { id: 14, path: '/dashboard/alerts',      label: 'Alerts & Notifications', icon: 'Bell' },
    ],
  },
  {
    id: 'dataset',
    label: 'Dataset Management',
    icon: 'Database',
    color: '#4F46E5',
    items: [
      { id: 15, path: '/dataset/catalog',       label: 'Dataset Catalog',      icon: 'FolderKanban' },
      { id: 16, path: '/dataset/upload',        label: 'Dataset Upload',       icon: 'Upload' },
      { id: 17, path: '/dataset/register',      label: 'Dataset Registration', icon: 'FilePlus' },
      { id: 18, path: '/dataset/preview',       label: 'Dataset Preview',      icon: 'Eye' },
      { id: 19, path: '/dataset/versions',      label: 'Version History',      icon: 'History' },
      { id: 20, path: '/dataset/validation',    label: 'Validation Results',   icon: 'CheckCircle2' },
      { id: 21, path: '/dataset/metadata',      label: 'Metadata Management',  icon: 'Tags' },
      { id: 22, path: '/dataset/lineage',       label: 'Data Lineage',         icon: 'GitBranch' },
      { id: 23, path: '/dataset/approval',      label: 'Approval Workflow',    icon: 'Workflow' },
      { id: 24, path: '/dataset/monitoring',    label: 'Dataset Monitoring',   icon: 'Activity' },
    ],
  },
  {
    id: 'dept',
    label: 'Department Integration',
    icon: 'Network',
    color: '#0891B2',
    items: [
      { id: 25, path: '/dept/registry',      label: 'Department Registry',  icon: 'Building' },
      { id: 26, path: '/dept/dashboard',     label: 'Integration Dashboard',icon: 'LayoutDashboard' },
      { id: 27, path: '/dept/api-config',    label: 'API Configuration',    icon: 'Cable' },
      { id: 28, path: '/dept/batch-import',  label: 'Batch Import',         icon: 'PackageOpen' },
      { id: 29, path: '/dept/realtime-sync', label: 'Real-Time Sync',       icon: 'RefreshCw' },
      { id: 30, path: '/dept/api-usage',     label: 'API Usage Dashboard',  icon: 'BarChart3' },
      { id: 31, path: '/dept/errors',        label: 'Integration Errors',   icon: 'AlertOctagon' },
      { id: 32, path: '/dept/health',        label: 'Department Health',    icon: 'HeartPulse' },
    ],
  },
  {
    id: 'quality',
    label: 'Data Quality',
    icon: 'ShieldCheck',
    color: '#059669',
    items: [
      { id: 33, path: '/quality/profiling',   label: 'Data Profiling',        icon: 'BarChart2' },
      { id: 34, path: '/quality/cleansing',   label: 'Cleansing Workbench',   icon: 'Sparkles' },
      { id: 35, path: '/quality/address',     label: 'Address Standardization', icon: 'MapPinned' },
      { id: 36, path: '/quality/name',        label: 'Name Standardization',  icon: 'CaseSensitive' },
      { id: 37, path: '/quality/duplicates',  label: 'Duplicate Detection',   icon: 'Copy' },
      { id: 38, path: '/quality/merge',       label: 'Record Merge',          icon: 'Merge' },
      { id: 39, path: '/quality/exceptions',  label: 'Exception Queue',       icon: 'AlertTriangle' },
      { id: 40, path: '/quality/scorecard',   label: 'DQ Scorecard',          icon: 'Trophy' },
    ],
  },
  {
    id: 'member',
    label: 'Member ID',
    icon: 'IdCard',
    color: '#7C3AED',
    items: [
      { id: 41, path: '/member/search',    label: 'Member Search',       icon: 'Search' },
      { id: 42, path: '/member/profile',   label: 'Member Profile',      icon: 'User' },
      { id: 43, path: '/member/generation',label: 'Member ID Generation',icon: 'Fingerprint' },
      { id: 44, path: '/member/matching',  label: 'Matching Review',     icon: 'GitCompare' },
      { id: 45, path: '/member/duplicates',label: 'Duplicate Resolution',icon: 'Users' },
      { id: 46, path: '/member/timeline',  label: 'Member Timeline',     icon: 'Clock' },
      { id: 47, path: '/member/audit',     label: 'Audit History',       icon: 'FileClock' },
    ],
  },
  {
    id: 'family',
    label: 'Family ID',
    icon: 'Users',
    color: '#DB2777',
    items: [
      { id: 48, path: '/family/search',       label: 'Family Search',      icon: 'Search' },
      { id: 49, path: '/family/profile',      label: 'Family Profile',     icon: 'Home' },
      { id: 50, path: '/family/tree',         label: 'Relationship Tree',  icon: 'Network' },
      { id: 51, path: '/family/formation',    label: 'Family Formation',   icon: 'UserPlus' },
      { id: 52, path: '/family/hof',          label: 'HoF Validation',     icon: 'Crown' },
      { id: 53, path: '/family/generation',   label: 'Family ID Generation',icon: 'Fingerprint' },
      { id: 54, path: '/family/merge',        label: 'Family Merge',       icon: 'Merge' },
      { id: 55, path: '/family/split',        label: 'Family Split',       icon: 'Split' },
      { id: 56, path: '/family/update',       label: 'Update Request',     icon: 'FilePen' },
      { id: 57, path: '/family/timeline',     label: 'Family Timeline',    icon: 'Clock' },
    ],
  },
  {
    id: 'registry',
    label: 'GCSR Registry',
    icon: 'ShieldCheck',
    color: '#059669',
    items: [
      { id: 58, path: '/registry/citizen-360',   label: 'Golden Citizen 360', icon: 'UserCheck' },
      { id: 59, path: '/registry/family-360',    label: 'Golden Family 360',  icon: 'HomeIcon' },
      { id: 60, path: '/registry/household',     label: 'Household Summary',  icon: 'Home' },
      { id: 61, path: '/registry/comparison',    label: 'Registry Comparison',icon: 'GitCompare' },
      { id: 62, path: '/registry/confidence',    label: 'Confidence Score',   icon: 'Gauge' },
      { id: 63, path: '/registry/history',       label: 'Change History',     icon: 'History' },
    ],
  },
  {
    id: 'enrichment',
    label: 'Department Enrichment',
    icon: 'Boxes',
    color: '#D97706',
    items: [
      { id: 64, path: '/enrichment/health',       label: 'Health Integration',      icon: 'HeartPulse' },
      { id: 65, path: '/enrichment/education',    label: 'Education Integration',   icon: 'GraduationCap' },
      { id: 66, path: '/enrichment/revenue',      label: 'Revenue & Land',          icon: 'Landmark' },
      { id: 67, path: '/enrichment/agriculture',  label: 'Agriculture Integration', icon: 'Wheat' },
      { id: 68, path: '/enrichment/social',       label: 'Social Welfare',          icon: 'HeartHandshake' },
      { id: 69, path: '/enrichment/banking',      label: 'Banking & DBT',           icon: 'Banknote' },
      { id: 70, path: '/enrichment/utility',      label: 'Utility Integration',     icon: 'Zap' },
      { id: 71, path: '/enrichment/address',      label: 'Address Verification',    icon: 'MapPin' },
      { id: 72, path: '/enrichment/dashboard',    label: 'Enrichment Dashboard',    icon: 'LayoutDashboard' },
    ],
  },
  {
    id: 'scheme',
    label: 'Scheme & DBT',
    icon: 'Banknote',
    color: '#B45309',
    items: [
      { id: 73, path: '/scheme/registry',       label: 'Scheme Registry',      icon: 'BookMarked' },
      { id: 74, path: '/scheme/eligibility',    label: 'Eligibility Engine',   icon: 'CheckCircle2' },
      { id: 75, path: '/scheme/recommendation', label: 'Scheme Recommendation',icon: 'Sparkles' },
      { id: 76, path: '/scheme/dbt-dashboard',  label: 'DBT Dashboard',        icon: 'BarChart3' },
      { id: 77, path: '/scheme/history',        label: 'Benefit History',      icon: 'History' },
      { id: 78, path: '/scheme/duplicate',      label: 'Duplicate Benefit',    icon: 'Copy' },
      { id: 79, path: '/scheme/saturation',     label: 'Scheme Saturation',    icon: 'Target' },
      { id: 80, path: '/scheme/leakage',        label: 'Welfare Leakage',      icon: 'AlertTriangle' },
    ],
  },
  {
    id: 'ai',
    label: 'AI & Analytics',
    icon: 'Brain',
    color: '#4F46E5',
    items: [
      { id: 81, path: '/ai/copilot',        label: 'AI Copilot',          icon: 'Bot' },
      { id: 82, path: '/ai/nl-query',       label: 'Natural Language Query', icon: 'MessageSquare' },
      { id: 83, path: '/ai/risk-score',     label: 'Citizen Risk Score',  icon: 'ShieldAlert' },
      { id: 84, path: '/ai/vulnerability',  label: 'Vulnerability Index', icon: 'Gauge' },
      { id: 85, path: '/ai/predictive',     label: 'Predictive Analytics',icon: 'TrendingUp' },
      { id: 86, path: '/ai/policy-sim',     label: 'Policy Simulator',    icon: 'Beaker' },
      { id: 87, path: '/ai/gis',            label: 'GIS Analytics',       icon: 'Map' },
      { id: 88, path: '/ai/insights',       label: 'AI Insight Explorer', icon: 'Lightbulb' },
    ],
  },
  {
    id: 'gov',
    label: 'Governance & Security',
    icon: 'Lock',
    color: '#B91C1C',
    items: [
      { id: 89, path: '/gov/consent',       label: 'Consent Management',   icon: 'ShieldCheck' },
      { id: 90, path: '/gov/access',        label: 'Access Requests',      icon: 'Key' },
      { id: 91, path: '/gov/roles',         label: 'Role & Permission',    icon: 'UserCog' },
      { id: 92, path: '/gov/api-access',    label: 'API Access Control',   icon: 'Cable' },
      { id: 93, path: '/gov/audit',         label: 'Audit Logs',           icon: 'FileClock' },
      { id: 94, path: '/gov/security',      label: 'Security Monitoring',  icon: 'ShieldAlert' },
      { id: 95, path: '/gov/data-sharing',  label: 'Data Sharing',         icon: 'Share2' },
      { id: 96, path: '/gov/compliance',    label: 'Compliance Dashboard', icon: 'BadgeCheck' },
    ],
  },
  {
    id: 'portal',
    label: 'Citizen Service Portal',
    icon: 'UserCircle2',
    color: '#059669',
    items: [
      { id: 97,  path: '/portal/login',        label: 'Citizen Login',       icon: 'LogIn' },
      { id: 98,  path: '/portal/search',       label: 'Search Family ID',    icon: 'Search' },
      { id: 99,  path: '/portal/view-family',  label: 'View Family Profile', icon: 'Users' },
      { id: 100, path: '/portal/update',       label: 'Update Member',       icon: 'FilePen' },
      { id: 101, path: '/portal/request-merge',label: 'Request Merge',       icon: 'Merge' },
      { id: 102, path: '/portal/request-split',label: 'Request Split',       icon: 'Split' },
      { id: 103, path: '/portal/correction',   label: 'Correction Request',  icon: 'FileEdit' },
      { id: 104, path: '/portal/track',        label: 'Track Request',       icon: 'PackageSearch' },
    ],
  },
  {
    id: 'admin',
    label: 'Administration',
    icon: 'Settings',
    color: '#475569',
    items: [
      { id: 105, path: '/admin/users',       label: 'User Management',     icon: 'Users' },
      { id: 106, path: '/admin/departments', label: 'Department Mgmt.',    icon: 'Building2' },
      { id: 107, path: '/admin/workflows',   label: 'Workflow Config',     icon: 'Workflow' },
      { id: 108, path: '/admin/rules',       label: 'Business Rules',      icon: 'ListChecks' },
      { id: 109, path: '/admin/notifications',label: 'Notifications',      icon: 'Bell' },
      { id: 110, path: '/admin/master-data', label: 'Master Data Config',  icon: 'Database' },
      { id: 111, path: '/admin/scheduler',   label: 'Scheduler & Jobs',    icon: 'CalendarClock' },
      { id: 112, path: '/admin/settings',    label: 'System Settings',     icon: 'Settings2' },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & Dashboards',
    icon: 'FileBarChart',
    color: '#7C3AED',
    items: [
      { id: 113, path: '/reports/executive',  label: 'Executive Reports',   icon: 'FileBarChart2' },
      { id: 114, path: '/reports/citizen',    label: 'Citizen Reports',     icon: 'Users' },
      { id: 115, path: '/reports/family',     label: 'Family Reports',      icon: 'Home' },
      { id: 116, path: '/reports/department', label: 'Department Reports',  icon: 'Building2' },
      { id: 117, path: '/reports/dbt',        label: 'DBT Reports',         icon: 'Banknote' },
      { id: 118, path: '/reports/quality',    label: 'Data Quality Reports',icon: 'ShieldCheck' },
      { id: 119, path: '/reports/ai',         label: 'AI Insights Reports', icon: 'Brain' },
      { id: 120, path: '/reports/builder',    label: 'Report Builder',      icon: 'PencilRuler' },
    ],
  },
];

// Flat list of all 120 screens for router
export const ALL_SCREENS = NAV.flatMap((m) => m.items.map((it) => ({ ...it, moduleId: m.id, moduleLabel: m.label })));
